version: '3.8'

services:
  axon-server:
    image: axoniq/axonserver
    container_name: axon-server
    hostname: axonserver
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
    ports:
      - 8024:8024
      - 8124:8124
  eventstore.db:
    image: eventstore/eventstore:21.2.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=System
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
  mongodb:
    image: mongo
    container_name: dewdrop-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dewdrop_db2
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KC_DB_DATABASE: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - backend

volumes:
  mongodb_data:
  postgres_data:

networks:
  backend:
    driver: bridge