axon:
  eventstore:
    type: eventstoredb
    eventstoredb:
      url: tcp://localhost:1113
      username: admin
      password: ""

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/axonxesdb
      database: axonxesdb

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
