server:
  port: 8080

spring:
  # MongoDB Configuration (Main Database)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dewdrop_db2
      auto-index-creation: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

axon:
  axonserver:
    enabled: false  # Disable Axon Server

  serializer:
    general: jackson
    events: jackson
    messages: jackson
  eventhandling:
    processors:
      asyncProcessor:
        mode: subscribing
        source: eventStore
  eventstore:
    eventStoreDB:
      uri: esdb://localhost:2113?tls=false  # EventStoreDB connection string
  aggregate:
    snapshot-threshold: 10  # Enables snapshotting after 10 events